sofastack/sofa-bolt

pom.xml, src/main/java/com/alipay/remoting/RemotingServer.java, src/test/java/com/alipay/remoting/RemotingServerTest.java
see issue #8 for change details
=> (tuning) refactor start logic of remoting server

LICENSE, src/main/java/com/alipay/remoting/log/BoltLoggerFactory.java, src/main/resources/com/alipay/remoting/log/log4j/log-conf.xml, src/main/resources/com/alipay/remoting/log/log4j2/log-conf.xml, src/main/resources/com/alipay/remoting/log/logback/log-conf.xml
add root logger fix #12
support commong log encode property, fix #13
=> (tuning) log conf modify

src/main/java/com/alipay/remoting/Configs.java, src/main/java/com/alipay/remoting/SystemProperties.java, src/main/java/com/alipay/remoting/rpc/RpcConnectionFactory.java, src/main/java/com/alipay/remoting/rpc/RpcServer.java, src/main/java/com/alipay/remoting/util/NettyEventLoopUtil.java
1. unify epoll judgement logic 
2. add system property for epoll level trigger
3. [important] change to use epoll by default, if sofa rpc upgraded, plz know this default behavior changed. @ujjboy 
@yangl please review also, thanks~
=> (tuning) tune some logic of epoll util, and modify some comments

.middleware-common/.travis.settings.xml, .travis.yml
=> (tuning) fix build error of jdk16 using travis ci

src/main/java/com/alipay/remoting/AbstractRemotingServer.java, src/main/java/com/alipay/remoting/RemotingServer.java, src/test/java/com/alipay/remoting/rpc/connectionmanage/ScheduledDisconnectStrategyTest.java, src/test/java/com/alipay/remoting/rpc/watermark/WaterMarkInitTest.java
* 修复AbstractRemotingServer#stop并发控制的BUG
* 移除了inited状态和init方法
* 修复了相关的单测
=> Fix the bug that RemotingServer can be closed repeatedly.

pom.xml, src/main/java/com/alipay/remoting/util/FutureTaskNotCompleted.java, src/main/java/com/alipay/remoting/util/FutureTaskUtil.java, src/main/java/com/alipay/remoting/util/RunStateRecordedFutureTask.java, src/test/java/com/alipay/remoting/rpc/connectionmanage/ScheduledDisconnectStrategyTest.java
fix: https://github.com/alipay/sofa-bolt/issues/96
=> Make getAfterRun un-block avoid deadlock.

README.md, pom.xml, src/main/java/com/alipay/remoting/AbstractLifeCycle.java, src/main/java/com/alipay/remoting/LifeCycle.java, src/main/java/com/alipay/remoting/LifeCycleException.java, src/main/java/com/alipay/remoting/ReconnectManager.java, src/main/java/com/alipay/remoting/rpc/RpcClient.java, src/main/java/com/alipay/remoting/util/FutureTaskNotCompleted.java, src/main/java/com/alipay/remoting/util/FutureTaskUtil.java, src/main/java/com/alipay/remoting/util/RunStateRecordedFutureTask.java, src/test/java/com/alipay/remoting/demo/RpcClientDemoByMain.java, src/test/java/com/alipay/remoting/demo/RpcServerDemoByMain.java, src/test/java/com/alipay/remoting/rpc/connectionmanage/ScheduledDisconnectStrategyTest.java
Bolt Verion 1.6.0 Plan: https://github.com/alipay/sofa-bolt/wiki/Bolt-1.6.0%E5%BC%80%E5%8F%91%E8%AE%A1%E5%88%92
1. 增加生命周期相关的组件
2. 修复潜在的NPE问题 https://github.com/alipay/sofa-bolt/issues/103
3. 重构优化一些细节代码， 如 https://github.com/alipay/sofa-bolt/issues/104
=> add LifeCycle component and refactor some code

src/main/java/com/alipay/remoting/DefaultConnectionManager.java
=> 1) 减少一次CHM.get 2)移除多余的判断条件

src/main/java/com/alipay/remoting/ConnectionEventHandler.java, src/main/java/com/alipay/remoting/ConnectionEventListener.java, src/main/java/com/alipay/remoting/ConnectionEventProcessor.java, src/main/java/com/alipay/remoting/ConnectionHeartbeatManager.java, src/main/java/com/alipay/remoting/constant/Constants.java, src/main/java/com/alipay/remoting/rpc/protocol/RpcHeartbeatTrigger.java
1. 修复RpcHeartbeatTrigger对超时的判断逻辑
2. 修复一些拼写和注释问题
=> fix https://github.com/alipay/sofa-bolt/issues/137

.travis.yml, pom.xml, src/main/java/com/alipay/remoting/rpc/RpcClient.java, src/main/java/com/alipay/remoting/rpc/protocol/RpcCommandDecoderV2.java, src/main/java/com/alipay/remoting/rpc/protocol/RpcCommandEncoderV2.java, src/test/java/com/alipay/remoting/rpc/connectionmanage/ReconnectManagerTest.java
fix https://github.com/alipay/sofa-bolt/issues/151
=> fix reconnection defect

pom.xml
修复漏洞 http://www.cnnvd.org.cn/web/xxk/ldxqById.tag?CNNVD=CNNVD-201909-1264
=> upgrade netty version to fix CNNVD-201909-1264 vulnerability

src/main/java/com/alipay/remoting/AbstractLifeCycle.java, src/main/java/com/alipay/remoting/AbstractRemotingServer.java, src/main/java/com/alipay/remoting/rpc/RpcServer.java, src/test/java/com/alipay/remoting/rpc/RpcServerTest.java
=> support server random port constructor. fix #196

src/main/java/com/alipay/remoting/DefaultConnectionManager.java
=> Optimization/connection manager constructor fix #153

src/main/java/com/alipay/remoting/AbstractLifeCycle.java, src/main/java/com/alipay/remoting/ReconnectManager.java, src/main/java/com/alipay/remoting/RemotingAddressParser.java, src/main/java/com/alipay/remoting/rpc/RpcAddressParser.java, src/main/java/com/alipay/remoting/rpc/RpcClient.java, src/main/java/com/alipay/remoting/rpc/RpcServer.java, src/test/java/com/alipay/remoting/rpc/LifeCycleTest.java
=> support availability check with life cycle. #195

src/main/java/com/alipay/remoting/NamedThreadFactory.java
fix nameThreadFactory spelling mistakes
=> fix spelling mistakes

src/main/resources/com/alipay/remoting/log/log4j2/log-conf.xml
=> optimized log4j2 config

plugins/wireshark/README.md, plugins/wireshark/bolt.lua, plugins/wireshark/install.bat, plugins/wireshark/install.sh
=> Add Wireshark plugin support

src/main/java/com/alipay/remoting/RejectedExecutionPolicy.java, src/main/java/com/alipay/remoting/RejectionProcessableInvokeCallback.java, src/main/java/com/alipay/remoting/rpc/RpcInvokeCallbackListener.java, src/test/java/com/alipay/remoting/rpc/callback/RejectionProcessableInvokeCallbackTest.java
- this feature is always existed in 1.6.^ client, so cherry pick this feature  from 'master' branch to make it possible to use in [1.5.10, ~] client
- fix testcase compile error
=> (feat) add rejection option in InvokeCallback

src/main/java/com/alipay/remoting/RpcAddress.java, src/main/java/com/alipay/remoting/rpc/RpcAddressParser.java, src/test/java/com/alipay/remoting/RpcAddressTest.java, src/test/java/com/alipay/remoting/inner/connection/ConnectionCreatingTest.java, src/test/java/com/alipay/remoting/rpc/RpcAddressParserTest.java
=> fix #263 add IPv6 Support

README.md
=> Update qrcode in README.md

src/main/java/com/alipay/remoting/Connection.java, src/test/java/com/alipay/remoting/inner/connection/ConnectionTest.java
Make Connection.isFine check Connection's closed state.  Related issue: #337
=> Add closed check in Connection's isFine
